name: Automatically set version tag

on:
  push:
    branches: [master]

jobs:
  tag-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set Git tag based on package.json version
        shell: bash
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          TAG_NAME="v$PACKAGE_VERSION"
          
          # Check if the tag does not exist already (otherwise, do nothing)
          if [ -z "$(git tag -l "$TAG_NAME")" ]; then
            git tag "$TAG_NAME"

            # Check if the version is not a pre-release
            if [[ ! "$PACKAGE_VERSION" =~ "-" ]]; then
              git tag "latest" -f
            fi
            
            git push --tags -f
          fi
